### ISSUE TITLE
Future of this package

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl-examples#1]
Should we keep this separate from odl, or move all code from here to `odl/examples`?

**Comment by kohr-h** [comment]
The current contents could very well be part of the main examples. I don't know if we want to add more complex stuff here maybe, but right now there's no real use for this.

**Comment by adler-j** [comment]
Maybe make `odl/examples` several folders?

"Start here" examples
`odl/examples/simple` 

Core examples and "templates"
`odl/examples/core`

Solvers
`odl/examples/solvers`

**Comment by kohr-h** [comment]
That's a good suggestion. Maybe `examples/intro` for the simple ones - or up to medium complexity but well-documented. And an intro chapter could use point to them.
